# Capsule configuration
# Copy to ~/.config/capsule/config.yaml (user) or .capsule/config.yaml (project).
# All fields are optional — missing fields use defaults shown below.
# Unknown fields are rejected (catches typos).
#
# Precedence (highest wins):
#   CLI flags > env vars > project config > user config > defaults
#
# See docs/config-schema.md for full reference.

runtime:
  # AI provider name. Must match a registered provider.
  # Env: CAPSULE_PROVIDER
  provider: claude    # default: claude

  # Maximum execution time per phase. Go duration format (e.g. 30s, 5m, 1h).
  # Env: CAPSULE_TIMEOUT
  timeout: 5m         # default: 5m

worktree:
  # Base directory for git worktrees, relative to project root.
  # Env: CAPSULE_WORKTREE_BASE_DIR
  base_dir: .capsule/worktrees   # default: .capsule/worktrees

pipeline:
  # Save checkpoints between pipeline phases for pause/resume.
  checkpoint: true    # default: false

  retry:
    # Maximum retry attempts per phase on transient failure.
    max_attempts: 3   # default: 3

    # Multiplier for exponential backoff between retries.
    backoff_factor: 1.5   # default: 1.0

campaign:
  # How to handle task failures: "abort" aborts the campaign, "continue" skips
  # the failed task and proceeds with remaining work.
  failure_mode: abort     # default: abort

  # Number of consecutive failures before halting the campaign regardless
  # of failure_mode.
  circuit_breaker: 3      # default: 3

  # Carry context (summaries, decisions) from completed tasks into subsequent
  # task runs within the same campaign.
  cross_run_context: true  # default: false
